import 'package:flutter/material.dart';

import '../../core/app_theme.dart';
import '../../data/mock_repo.dart';
import '../../data/models/user.dart';
import '../../widgets/pawneo_system_sheet.dart';
import '../../widgets/stat_card.dart';

class ProfilePage extends StatefulWidget {
  final VoidCallback onLogout;
  const ProfilePage({super.key, required this.onLogout});

  @override
  State<ProfilePage> createState() => _ProfilePageState();
}

class _ProfilePageState extends State<ProfilePage> {
  int _tab = 0;

  @override
  Widget build(BuildContext context) {
    final user = MockRepo.user;

    return Scaffold(
      appBar: AppBar(
        title: const Text('Profile'),
        actions: [
          IconButton(
            icon: const Icon(Icons.settings_outlined),
            onPressed: () => _system(
              'Profile settings',
              'Manage notifications, privacy, payout rules and custody preferences from one place.',
              type: PawneoNoticeType.info,
            ),
          ),
        ],
      ),
      body: ListView(
        padding: const EdgeInsets.fromLTRB(20, 12, 20, 120),
        children: [
          _ProfileHero(user: user),
          const SizedBox(height: 18),
          _ProfileTabs(
            selected: _tab,
            onChanged: (i) => setState(() => _tab = i),
          ),
          const SizedBox(height: 18),
          AnimatedSwitcher(
            duration: const Duration(milliseconds: 260),
            child: KeyedSubtree(
              key: ValueKey(_tab),
              child: switch (_tab) {
                0 => _OverviewTab(user: user),
                1 => _TrustTab(user: user, onAction: _system),
                _ => _RewardsTab(onAction: _system),
              },
            ),
          ),
          const SizedBox(height: 24),
          _SettingsGroup(
            onTap: (label) => _system(
              label,
              _copyFor(label),
              type: label == 'Security & privacy' ? PawneoNoticeType.warning : PawneoNoticeType.info,
            ),
            onLogout: widget.onLogout,
          ),
        ],
      ),
    );
  }

  String _copyFor(String label) {
    switch (label) {
      case 'Payout settings':
        return 'Choose payout currency, bank account and automatic reinvestment preferences for yield generated by your collateral.';
      case 'Security & privacy':
        return 'Biometric access, device approvals and data controls keep Pawneo secure before high-value objects are pledged.';
      case 'Notifications':
        return 'Get alerts for valuation changes, custody events, pool openings and payout cycles.';
      case 'Legal & terms':
        return 'Review custody, collateral, insurance and execution terms before activating a pawning agreement.';
      default:
        return 'The Pawneo support team can help with valuations, shipping, insurance and portfolio matching.';
    }
  }

  void _system(
    String title,
    String message, {
    PawneoNoticeType type = PawneoNoticeType.info,
  }) {
    PawneoSystemSheet.show(
      context,
      type: type,
      title: title,
      message: message,
      primaryLabel: 'Got it',
    );
  }
}

class _ProfileHero extends StatelessWidget {
  final UserProfile user;
  const _ProfileHero({required this.user});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Container(
      decoration: BoxDecoration(
        gradient: AppGradients.hero,
        borderRadius: BorderRadius.circular(30),
        boxShadow: AppShadows.primary,
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(30),
        child: Stack(
          children: [
            Positioned(
              right: -70,
              top: -70,
              child: Container(
                width: 190,
                height: 190,
                decoration: BoxDecoration(
                  shape: BoxShape.circle,
                  color: Colors.white.withOpacity(0.07),
                ),
              ),
            ),
            Padding(
              padding: const EdgeInsets.all(22),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      CircleAvatar(
                        radius: 35,
                        backgroundColor: Colors.white.withOpacity(0.16),
                        child: const Text(
                          'J',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 30,
                            fontWeight: FontWeight.w900,
                          ),
                        ),
                      ),
                      const SizedBox(width: 16),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              user.name,
                              style: theme.textTheme.headlineSmall?.copyWith(
                                color: Colors.white,
                                letterSpacing: -0.3,
                              ),
                            ),
                            const SizedBox(height: 4),
                            Text(
                              user.email,
                              style: theme.textTheme.bodySmall?.copyWith(color: Colors.white70),
                            ),
                            const SizedBox(height: 8),
                            Row(
                              children: [
                                const Icon(Icons.location_on_outlined, size: 16, color: Colors.white70),
                                const SizedBox(width: 4),
                                Text(
                                  user.location,
                                  style: theme.textTheme.bodySmall?.copyWith(color: Colors.white70),
                                ),
                              ],
                            ),
                          ],
                        ),
                      ),
                      Container(
                        padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 7),
                        decoration: BoxDecoration(
                          color: const Color(0xFF7DF5D0).withOpacity(0.16),
                          borderRadius: BorderRadius.circular(999),
                        ),
                        child: const Text(
                          'TRUST 9.2',
                          style: TextStyle(
                            color: Color(0xFF7DF5D0),
                            fontSize: 11,
                            fontWeight: FontWeight.w900,
                          ),
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 22),
                  Row(
                    children: [
                      Expanded(child: _HeroMetric(label: 'Collateral', value: money(user.totalCollateralValue))),
                      const SizedBox(width: 12),
                      Expanded(child: _HeroMetric(label: 'Earned', value: '+${money(user.totalEarnings)}')),
                      const SizedBox(width: 12),
                      Expanded(child: _HeroMetric(label: 'Objects', value: '${user.activeItems}')),
                    ],
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _HeroMetric extends StatelessWidget {
  final String label;
  final String value;
  const _HeroMetric({required this.label, required this.value});

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: Colors.white.withOpacity(0.12),
        borderRadius: BorderRadius.circular(18),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(value, style: Theme.of(context).textTheme.titleMedium?.copyWith(color: Colors.white, fontWeight: FontWeight.w900)),
          const SizedBox(height: 3),
          Text(label, style: Theme.of(context).textTheme.bodySmall?.copyWith(color: Colors.white70, fontSize: 11)),
        ],
      ),
    );
  }
}

class _ProfileTabs extends StatelessWidget {
  final int selected;
  final ValueChanged<int> onChanged;
  const _ProfileTabs({required this.selected, required this.onChanged});

  @override
  Widget build(BuildContext context) {
    final labels = ['Overview', 'Trust', 'Rewards'];
    return Container(
      padding: const EdgeInsets.all(5),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(22),
        border: Border.all(color: Theme.of(context).colorScheme.outlineVariant.withOpacity(0.75)),
      ),
      child: Row(
        children: List.generate(labels.length, (i) {
          final active = i == selected;
          return Expanded(
            child: GestureDetector(
              onTap: () => onChanged(i),
              child: AnimatedContainer(
                duration: const Duration(milliseconds: 220),
                padding: const EdgeInsets.symmetric(vertical: 12),
                decoration: BoxDecoration(
                  gradient: active ? AppGradients.accent : null,
                  borderRadius: BorderRadius.circular(17),
                ),
                child: Text(
                  labels[i],
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: active ? Colors.white : const Color(0xFF64748B),
                    fontWeight: FontWeight.w900,
                    fontSize: 13,
                  ),
                ),
              ),
            ),
          );
        }),
      ),
    );
  }
}

class _OverviewTab extends StatelessWidget {
  final UserProfile user;
  const _OverviewTab({required this.user});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Row(
          children: [
            Expanded(
              child: StatCard(
                title: 'Collateral value',
                value: money(user.totalCollateralValue),
                subtitle: '${user.activeItems} active items',
                icon: Icons.shield_rounded,
              ),
            ),
            const SizedBox(width: 16),
            Expanded(
              child: StatCard(
                title: 'Pending payout',
                value: money(user.pendingEarnings),
                subtitle: 'Next cycle',
                icon: Icons.schedule_rounded,
                accent: Colors.orange.shade700,
              ),
            ),
          ],
        ),
        const SizedBox(height: 16),
        _TimelineCard(),
      ],
    );
  }
}

class _TrustTab extends StatelessWidget {
  final UserProfile user;
  final void Function(String, String, {PawneoNoticeType type}) onAction;
  const _TrustTab({required this.user, required this.onAction});

  @override
  Widget build(BuildContext context) {
    final joined = '${user.memberSince.month}/${user.memberSince.year}';
    return Column(
      children: [
        _ActionCard(
          icon: Icons.verified_user_rounded,
          title: 'Identity verified',
          subtitle: 'KYC complete · Member since $joined',
          action: 'View trust file',
          color: Colors.green.shade600,
          onTap: () => onAction(
            'Trust file',
            'Identity, phone, device and location checks are complete. This increases collateral limits and lowers custody friction.',
            type: PawneoNoticeType.success,
          ),
        ),
        const SizedBox(height: 12),
        _ActionCard(
          icon: Icons.inventory_rounded,
          title: 'Custody preferences',
          subtitle: 'Madrid drop-off enabled · insured shipping available',
          action: 'Manage custody',
          color: Colors.indigo.shade600,
          onTap: () => onAction(
            'Custody preferences',
            'Choose whether each object is shipped, dropped off or stored with an approved custody partner.',
          ),
        ),
        const SizedBox(height: 12),
        _ActionCard(
          icon: Icons.lock_rounded,
          title: 'Security mode',
          subtitle: 'Biometric login, trusted device and payout lock active',
          action: 'Review security',
          color: Colors.orange.shade700,
          onTap: () => onAction(
            'Security mode',
            'For high-value pawning, Pawneo requires biometric authentication and payout confirmation before changes are applied.',
            type: PawneoNoticeType.warning,
          ),
        ),
      ],
    );
  }
}

class _RewardsTab extends StatelessWidget {
  final void Function(String, String, {PawneoNoticeType type}) onAction;
  const _RewardsTab({required this.onAction});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: double.infinity,
          padding: const EdgeInsets.all(20),
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(24),
            border: Border.all(color: Theme.of(context).colorScheme.outlineVariant.withOpacity(0.7)),
            boxShadow: const [BoxShadow(color: Color(0x0F1B2B5B), blurRadius: 20, offset: Offset(0, 12))],
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text('Viral loop', style: Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.w900)),
              const SizedBox(height: 6),
              Text('Share Pawneo Score cards and earn boosts when friends pawn their first object.', style: Theme.of(context).textTheme.bodyMedium),
              const SizedBox(height: 18),
              Row(
                children: const [
                  Expanded(child: _RewardMetric(value: '3', label: 'Invites')),
                  SizedBox(width: 12),
                  Expanded(child: _RewardMetric(value: '+0.4%', label: 'Yield boost')),
                  SizedBox(width: 12),
                  Expanded(child: _RewardMetric(value: '\$25', label: 'Credit')),
                ],
              ),
              const SizedBox(height: 18),
              SizedBox(
                width: double.infinity,
                child: FilledButton.icon(
                  onPressed: () => onAction(
                    'Share card ready',
                    'Your next confirmed object will generate a shareable card with value, score and estimated credit line.',
                    type: PawneoNoticeType.action,
                  ),
                  icon: const Icon(Icons.ios_share_rounded),
                  label: const Text('Generate share card'),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}

class _RewardMetric extends StatelessWidget {
  final String value;
  final String label;
  const _RewardMetric({required this.value, required this.label});

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: const Color(0xFFF6F8FF),
        borderRadius: BorderRadius.circular(18),
      ),
      child: Column(
        children: [
          Text(value, style: Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.w900)),
          const SizedBox(height: 2),
          Text(label, textAlign: TextAlign.center, style: Theme.of(context).textTheme.bodySmall),
        ],
      ),
    );
  }
}

class _TimelineCard extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final events = [
      ('MacBook Pro valuation', 'Score 8.8 · ready to pawnear'),
      ('Yield payout pending', '+${money(48)} expected next cycle'),
      ('Iberia pool match', 'Micro-lending demand remains high'),
    ];
    return Card(
      margin: EdgeInsets.zero,
      child: Padding(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text('Activity timeline', style: Theme.of(context).textTheme.titleMedium?.copyWith(fontWeight: FontWeight.w900)),
            const SizedBox(height: 14),
            ...events.map((e) => Padding(
                  padding: const EdgeInsets.only(bottom: 14),
                  child: Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Container(
                        width: 10,
                        height: 10,
                        margin: const EdgeInsets.only(top: 5),
                        decoration: BoxDecoration(color: Theme.of(context).colorScheme.primary, shape: BoxShape.circle),
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(e.$1, style: const TextStyle(fontWeight: FontWeight.w800)),
                            const SizedBox(height: 2),
                            Text(e.$2, style: Theme.of(context).textTheme.bodySmall),
                          ],
                        ),
                      ),
                    ],
                  ),
                )),
          ],
        ),
      ),
    );
  }
}

class _ActionCard extends StatelessWidget {
  final IconData icon;
  final String title;
  final String subtitle;
  final String action;
  final Color color;
  final VoidCallback onTap;

  const _ActionCard({
    required this.icon,
    required this.title,
    required this.subtitle,
    required this.action,
    required this.color,
    required this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(18),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(24),
        border: Border.all(color: Theme.of(context).colorScheme.outlineVariant.withOpacity(0.7)),
        boxShadow: const [BoxShadow(color: Color(0x0F1B2B5B), blurRadius: 20, offset: Offset(0, 12))],
      ),
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(color: color.withOpacity(0.12), borderRadius: BorderRadius.circular(16)),
            child: Icon(icon, color: color),
          ),
          const SizedBox(width: 14),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(title, style: Theme.of(context).textTheme.titleSmall?.copyWith(fontWeight: FontWeight.w900)),
                const SizedBox(height: 3),
                Text(subtitle, style: Theme.of(context).textTheme.bodySmall),
                const SizedBox(height: 8),
                GestureDetector(
                  onTap: onTap,
                  child: Text(action, style: TextStyle(color: Theme.of(context).colorScheme.primary, fontWeight: FontWeight.w900)),
                ),
              ],
            ),
          ),
          const Icon(Icons.chevron_right_rounded),
        ],
      ),
    );
  }
}

class _SettingsGroup extends StatelessWidget {
  const _SettingsGroup({required this.onTap, required this.onLogout});

  final ValueChanged<String> onTap;
  final VoidCallback onLogout;

  @override
  Widget build(BuildContext context) {
    final items = [
      _SettingItem(Icons.account_balance_rounded, 'Payout settings'),
      _SettingItem(Icons.security_rounded, 'Security & privacy'),
      _SettingItem(Icons.notifications_active_rounded, 'Notifications'),
      _SettingItem(Icons.description_outlined, 'Legal & terms'),
      _SettingItem(Icons.help_outline_rounded, 'Help & support'),
    ];

    return Card(
      margin: EdgeInsets.zero,
      child: Column(
        children: [
          ...ListTile.divideTiles(
            context: context,
            tiles: items.map(
              (item) => ListTile(
                leading: Icon(item.icon),
                title: Text(item.label, style: const TextStyle(fontWeight: FontWeight.w700)),
                trailing: const Icon(Icons.chevron_right_rounded),
                onTap: () => onTap(item.label),
              ),
            ),
          ),
          const Divider(),
          ListTile(
            leading: const Icon(Icons.logout_rounded, color: Colors.red),
            title: const Text('Sign out', style: TextStyle(fontWeight: FontWeight.w700, color: Colors.red)),
            trailing: const Icon(Icons.chevron_right_rounded, color: Colors.red),
            onTap: onLogout,
          ),
        ],
      ),
    );
  }
}

class _SettingItem {
  final IconData icon;
  final String label;
  const _SettingItem(this.icon, this.label);
}
